jd-orion/ccms

packages/UIs/ccms-antd/src/components/detail/image/index.less, packages/UIs/ccms-antd/src/components/detail/image/index.tsx
=> feat: 详情页图片新增预览

packages/UIs/ccms-antd/src/components/detail/iframe/index.less, packages/UIs/ccms-antd/src/components/detail/iframe/index.tsx, packages/UIs/ccms-antd/src/components/detail/image/index.less, packages/UIs/ccms-antd/src/components/detail/image/index.tsx, packages/UIs/ccms-antd/src/components/detail/index.tsx, packages/core/src/components/detail/iframe/index.tsx, packages/core/src/components/detail/image/index.tsx, packages/core/src/components/detail/index.tsx, packages/core/src/index.tsx, packages/editor/src/config/detail/iframe.ts, packages/editor/src/config/detail/image.ts, packages/editor/src/config/detail/index.ts, packages/editor/src/config/detail/statement.ts
- 支持iframe展示，可配置宽高、url字段拼接
- 新增图片组展示，支持对象型数组key的配置
=> feat: 详情页自定义组件iframe集成 / 详情页图片组展示

packages/UIs/ccms-antd/src/components/detail/common.ts
=> 16 feature request 详情页分栏添加换行

packages/UIs/ccms-antd/src/components/detail/table/index.less, packages/UIs/ccms-antd/src/components/detail/table/index.tsx, packages/core/src/components/detail/table/index.tsx, packages/editor/src/config/detail/table.ts
- 新增表格宽度配置项
- 优化表单创建时默认 1000 值为动态获取
=> feat: 新增详情表格支持宽度配置，优化配置详情表单时宽度不能自适应。

packages/editor/src/config/detail/table.ts, packages/editor/src/steps/table.ts
=> fix: 下拉按钮组展示条件加粗以及label添加

packages/core/src/components/tableColumns/enum/index.tsx, packages/core/src/util/enumeration.ts
- 兼容1.3.0以上版本的表格选项配置值
- 代码格式修改
=> fix: 兼容1.3.0以下版本的表格选项配置值

packages/core/src/components/formFields/table/common/form.tsx
=> fix: 修复表单子表格赋值逻辑不支持空路径的问题

packages/UIs/ccms-antd/src/util/operation.tsx
=> fix: 修复OperationHelper组件UI展示失败的问题

packages/core/src/components/tableColumns/enum/index.tsx
=> fix: 优化1.3.0以下老版本的表格option.data下的值为key

packages/core/src/util/produce.tsx
=> fix: product中merge操作入参选用错误

packages/core/src/components/detail/detailInfo/index.tsx, packages/core/src/components/detail/iframe/index.tsx, packages/core/src/components/detail/link/index.tsx, packages/core/src/components/detail/statement/index.tsx, packages/core/src/steps/common.tsx, packages/core/src/steps/detail/index.tsx, packages/core/src/steps/fetch/index.tsx, packages/core/src/steps/header/index.tsx
=> perf: 补充方法中record的参数

packages/UIs/ccms-antd/src/components/detail/code/index.less, packages/UIs/ccms-antd/src/components/detail/code/index.tsx, packages/UIs/ccms-antd/src/components/detail/index.tsx, packages/core/src/components/detail/code/index.tsx, packages/core/src/components/detail/index.tsx, packages/core/src/index.tsx, packages/editor/src/config/detail/code.ts, packages/editor/src/config/detail/index.ts
```javascript
steps: [
{
type: 'fetch',
interface: {
url: '',
method: 'GET',
withCredentials: true,
condition: {
enable: false,
field: 'code',
value: 1000,
success: { type: 'modal', content: { type: 'static', content: '成功' } },
fail: { type: 'modal', content: { type: 'field', field: 'msg' } }
},
cache: { disabled: true }
},
nextStep: false
},
{ type: 'header' },
{
type: 'detail',
fields: [
{
type: 'code',
field: 'code',
label: 'code',
codeType: 'json',
height: 200,
theme: 'black',
fullScreen: false
}
],
columns: {},
defaultValue: { source: 'source', field: '' }
}
]
}
```
=> feat: 详情页代码编辑器组件

packages/UIs/ccms-antd/src/steps/form/index.less, packages/UIs/ccms-antd/src/steps/form/index.tsx
=> pref: 优化群组表单样式

packages/UIs/ccms-antd/src/components/formFields/select/single/index.tsx, packages/core/src/components/formFields/select/common.tsx, packages/core/src/components/formFields/select/single/index.tsx, packages/core/src/util/enumeration.ts, packages/editor/src/config/common/EnumerationConfig.ts
=> feat: 支持选项/枚举值禁用

packages/UIs/ccms-antd/src/components/formFields/table/index.tsx, packages/core/src/components/formFields/container.tsx, packages/core/src/components/formFields/table/common/form.tsx, packages/core/src/components/formFields/table/index.tsx
=> feat: 补充主键冲突校验；列、子表单的展示条件逻辑。

package.json, packages/editor/package.json, packages/editor/src/component/ConfigJSON/index.tsx, packages/editor/webpack.common.js
=> perf: 优化编辑器的编辑器样式引用

packages/editor/package.json, packages/editor/src/component/ConfigJSON/index.tsx, packages/editor/webpack.common.js
=> perf: 更新编辑器样式

packages/core/src/components/detail/custom/index.tsx, packages/core/src/components/formFields/custom/index.tsx, packages/core/src/components/tableColumns/custom/index.tsx
=> feat: 补充自定义组件逻辑，详情和表格自定义组件增加版本相关信息

packages/core/src/components/formFields/form/index.tsx, packages/core/src/components/formFields/table/index.tsx, packages/core/src/util/produce.tsx
现象：修复子表单列表已删除数据仍被校验的问题
逻辑：修复数据不可变中，对数组类型数据进行`push`/`splice`/`sort`操作时，数据路径为根节点时出错的问题。
```javascript
steps: [
{ type: 'header' },
{
type: 'form',
columns: {},
fields: [
{
label: 'a',
field: 'a',
type: 'form',
canInsert: true,
canRemove: true,
fields: [{ label: 'a', field: 'a', type: 'text', maxLength: 4 }]
}
],
actions: [
{ type: 'submit', label: '提交', mode: 'primary', submitValidate: false },
{ type: 'cancel', label: '取消', mode: 'normal', submitValidate: false }
],
rightTopActions: [],
defaultValue: { source: 'data', field: '' }
},
{
type: 'fetch',
interface: {
url: '',
method: 'GET',
withCredentials: true,
condition: { …
```
=> fix: 修复子表单列表已删除数据仍被校验的问题

packages/core/src/components/formFields/text/index.tsx, packages/editor/src/app.less, packages/editor/src/app.tsx, packages/editor/src/indexDev.tsx, packages/editor/src/steps/index.tsx
1.编辑器新增自定义步骤，支持编辑器手动配置非标准页面流程。
2.优化普通文本录入的校验逻辑
```javascript
steps: []
}
```
=> feat: 编辑器新增自定义步骤

packages/core/src/components/detail/enum/index.tsx, packages/core/src/util/enumeration.ts
=> fix: 兼容数据为空的逻辑
